server:
  port: 9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServerA:9200/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-cloud-gateway
    #网关的配置
  cloud:
    gateway:
      routes: #配置路由
      - id: service-page-router
        uri: lb://lagou-service-page
        predicates: #当断言成功后，交给某一个微服务处理时使用的是转发
          - Path=/page/**
        filters:
        - StripPrefix=1
      - id: service-product-router
        uri: lb://lagou-service-product
        predicates:
          - Path=/product/**
        filters:
          - StripPrefix=1



